FROM alpine:3.18

RUN apk add --update-cache \
	python3 \
	curl \
	which \
	bash \
	&& rm -rf /var/cache/apk/*

RUN curl -sSL https://sdk.cloud.google.com | bash

ENV PATH $PATH:/root/google-cloud-sdk/bin

ENTRYPOINT [ "gcloud" ]
